# Config File for toring oauth2 based information

# Github Client and Secret
id: 260209c808c421b6e630
secret: cb9c4b4f6b4cb5c24923338d436f8ea879bcaf00
auth_url: https://github.com/login/oauth/authorize
token_url: https://github.com/login/oauth/access_token
basic_url: https://api.github.com
redirect_url: http://127.0.0.1:3000/git/oauth2/callback